import type { ReactNode } from 'react';

import type { Metadata } from 'next';
import { Lora } from 'next/font/google';

import { ThemeProvider } from 'next-themes';

import '@/app/globals.css';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/utils';

import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const lora = Lora({
    weight: '400',
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-serif'
});

export const viewport = {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    themeColor: [{ media: '(prefers-color-scheme: light)' }, { media: '(prefers-color-scheme: dark)' }]
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        // ? https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
        // ? https://react.dev/reference/react-dom/client/hydrateRoot#suppressing-unavoidable-hydration-mismatch-errors
        <html suppressHydrationWarning lang='en'>
            <body
                className={cn(
                    `${GeistSans.variable} ${GeistMono.variable} ${lora.variable} font-sans`,
                    'overscroll-none whitespace-pre-line antialiased'
                )}>
                <ThemeProvider attribute='class'>
                    {children}
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
};

export default Layout;
